services:
  database:
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=koko
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=koko
    networks:
      - db

  koko-api:
    container_name: koko-api
    image: kokoaiye/koko-api
    ports:
      - 8088:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/customer
    networks:
      - db
    depends_on:
      - database
#    command:
#      - --spring.datasource.url=jdbc:postgresql://database:5432/customer


networks:
  db:
    driver: bridge

volumes:
  pgdata:

#version: '3.8'
#services:
#  db:
#    image: postgres:14.1-alpine
#    restart: always
#    environment:
#      - POSTGRES_USER=koko
#      - POSTGRES_PASSWORD=password
#      - PGDATA=/data/postgres
#    ports:
#      - '5432:5432'
#    volumes:
#      - db:/data/postgres
#volumes:
#  db:
#    driver: local


#services:
#  db:
#    container_name: postgres
#    image: posgres
#    environment:
#      POSTGRES_USER: koko
#      POSTGRES_PASSWORD: password
#      PGDATA: /data/postgres
#    volumes:
#      - db:/data/postgres
#    ports:
#      - "5432:5432"
#    networks:
#      - db
#    restart: unless-stopped
#
#networks:
#  db:
#    driver: bridge
#
#volumes:
#  db: